### ISSUE TITLE
errors using full_config generator

### ISSUE THREAD

**Issue by bobics** [kristianmandrup/cream#7]
I see the error output below when running the full_config generator.  I'm on Rails 3.0.3, cream 0.8.1, with brand new empty Rails project (only thing I've added is the cream dependency to the Gemfile).

$rails g cream:full_config --strategy admin_flag --admin-user --orm AR

/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:4: warning: already initialized constant DIR
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:88: warning: already initialized constant DIR
[Rails3::Assist::Logging]
rails g cream:app --orm AR
         run  rails g cream:app --orm AR from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:4: warning: already initialized constant DIR
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:88: warning: already initialized constant DIR
views: 
[Rails3::Assist::Logging]
insert_flash_displayer: alert
views: 
insert_flash_displayer: notice
views: 
rails g devise:config --orm AR
         run  rails g devise:config --orm AR from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:4: warning: already initialized constant DIR
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails3_artifactor-0.3.1/lib/rails3_artifactor/artifact/file_name/view.rb:88: warning: already initialized constant DIR
Configuring devise gems for AR
[Rails3::Assist::Logging]
Adding gem: devise
     gemfile  devise
Orm AR is not currently supported by Cream. You are most welcome to provide a Cream adapter for that ORM ;)
         run  bundle install from "."
Using rake (0.8.7) 
Using abstract (1.0.0) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.13) 
Using rack-test (0.5.6) 
Using tzinfo (0.3.23) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.12) 
Using actionmailer (3.0.3) 
Using arel (2.0.6) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using bcrypt-ruby (2.1.2) 
Using bundler (1.0.7) 
Using cancan (1.4.1) 
Using log4r (1.1.9) 
Using require_all (1.2.0) 
Using mocha (0.9.10) 
Using sugar-high (0.3.1) 
Using logging_assist (0.1.6) 
Using thor (0.14.6) 
Using railties (3.0.3) 
Using rails (3.0.3) 
Using migration_assist (0.1.7) 
Using rails3_assist (0.3.3) 
Using rspec-core (2.3.1) 
Using diff-lcs (1.1.2) 
Using rspec-expectations (2.3.0) 
Using rspec-mocks (2.3.0) 
Using rspec (2.3.0) 
Using rails3_artifactor (0.3.1) 
Using cancan-permits (0.3.6) 
Using code-spec (0.2.9) 
Using file-spec (0.1.4) 
Using rails-app-spec (0.3.2) 
Using test-unit (2.1.2) 
Using generator-spec (0.7.1) 
Using r3_plugin_toolbox (0.4.0) 
Using cancan-rest-links (0.2.0) 
Using warden (1.0.3) 
Using devise (1.1.5) 
Using devise-links (0.2.1) 
Using cream (0.8.1) 
Using sqlite3-ruby (1.3.2) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
initializers/devise.rb was NOT found so devise:install will now be run
rails g devise:install
         run  rails g devise:install from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml
# 

Some setup you must do manually if you haven't yet:
1. Setup default url options for your specific environment. Here is an
    example of development environment:
   
      config.action_mailer.default_url_options = { :host => 'localhost:3000' }
   
    This is a required Rails configuration. In production it must be the
    actual host of your application
2. Ensure you have defined root_url to _something_ in your config/routes.rb.
    For example:
   
      root :to => "home#index"
3. Ensure you have flash messages in app/views/layouts/application.html.erb.
    For example:
   
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
# 

Configuring orm: [AR]
require 'devise/orm/AR' already in devise.rb initializer
Configuring: devise mailer
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:126: warning: regexp has invalid interval
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:126: warning: regexp has `}' without escape
Configuring: devise authentication filter
rails g devise:users --orm AR --admin-user --no-gems
         run  rails g devise:users --orm AR --admin-user --no-gems from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require': no such file to load -- devise/orm/ (LoadError)
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:15
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise.rb:183:in`setup'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:3
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:201
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:50:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /Users/bobics/Development/testapps/cream_test/config/environment.rb:5
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:103:in`require_environment!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:16
    from script/rails:6:in `require'
    from script/rails:6
rails g cancan:config --orm AR --no-gems
         run  rails g cancan:config --orm AR --no-gems from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require': no such file to load -- devise/orm/ (LoadError)
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:15
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise.rb:183:in`setup'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:3
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:201
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:50:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /Users/bobics/Development/testapps/cream_test/config/environment.rb:5
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:103:in`require_environment!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:16
    from script/rails:6:in `require'
    from script/rails:6
rails g roles:config --orm AR --roles guest admin --strategy admin_flag
         run  rails g roles:config --orm AR --roles guest admin --strategy admin_flag from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require': no such file to load -- devise/orm/ (LoadError)
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:15
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise.rb:183:in`setup'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:3
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:201
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:50:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /Users/bobics/Development/testapps/cream_test/config/environment.rb:5
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:103:in`require_environment!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:16
    from script/rails:6:in `require'
    from script/rails:6
rails g permits:config --orm AR --roles guest admin --no-gems
         run  rails g permits:config --orm AR --roles guest admin --no-gems from "."
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require': no such file to load -- devise/orm/ (LoadError)
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:15
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise.rb:183:in`setup'
    from /Users/bobics/Development/testapps/cream_test/config/initializers/devise.rb:3
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:201
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/engine.rb:200
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `run'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:50:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:134:in `initialize!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /Users/bobics/Development/testapps/cream_test/config/environment.rb:5
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:103:in`require_environment!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:16
    from script/rails:6:in `require'
    from script/rails:6

**Comment by kristianmandrup** [comment]
Wow! What a stacktrace! Well, I just pushed a few updated generators with better validation and handling of the ORM parameter. I have never seen that constant conflict error before when testing cream. I will take a look at it ASAP.
Thanks!

**Comment by kristianmandrup** [comment]
I just tested it with my latest version that I've also just release (cream 0.8.2)

Don't mind the iconv errors, this is a ruby 1.9.3-head issue. 

<pre>
kristian-mandrups-macbook-pro:test-ar-cream kristianconsult$ rails g cream:full_config --strategy admin_flag --admin-user --orm AR
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
rails g cream:app --orm active_record
         run  rails g cream:app --orm active_record from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
insert_flash_displayer: alert
insert_flash_displayer: notice
rails g devise:config --orm active_record
         run  rails g devise:config --orm active_record from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
Configuring devise gems for active_record
[Rails3::Assist::Logging]
Adding gem: devise
     gemfile  devise
Orm active_record is not currently supported by Cream. You are most welcome to provide a Cream adapter for that ORM ;)
         run  bundle install from "."
Using rake (0.8.7) 
Using abstract (1.0.0) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.13) 
Using rack-test (0.5.6) 
Using tzinfo (0.3.23) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.12) 
Using actionmailer (3.0.3) 
Using arel (2.0.6) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using bcrypt-ruby (2.1.2) 
Using bundler (1.0.7) 
Using cancan (1.4.1) 
Using log4r (1.1.9) 
Using require_all (1.2.0) 
Using mocha (0.9.10) 
Using sugar-high (0.3.1) 
Using logging_assist (0.1.6) 
Using thor (0.14.6) 
Using railties (3.0.3) 
Using rails (3.0.3) 
Using migration_assist (0.1.7) 
Using rails3_assist (0.3.3) 
Using rspec-core (2.3.1) 
Using diff-lcs (1.1.2) 
Using rspec-expectations (2.3.0) 
Using rspec-mocks (2.3.0) 
Using rspec (2.3.0) 
Using rails3_artifactor (0.3.2) 
Using cancan-permits (0.3.6) 
Using code-spec (0.2.9) 
Using file-spec (0.1.4) 
Using rails-app-spec (0.3.2) 
Using test-unit (2.1.2) 
Using generator-spec (0.7.1) 
Using r3_plugin_toolbox (0.4.0) 
Using cancan-rest-links (0.2.0) 
Using warden (1.0.3) 
Using devise (1.1.5) 
Using devise-links (0.2.1) 
Using cream (0.8.1) 
Your bundle is complete! It was installed into /Users/kristianconsult/.rvm/gems/ruby-1.9.3-head
initializers/devise.rb was NOT found so devise:install will now be run
rails g devise:install
         run  rails g devise:install from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml

===============================================================================

Some setup you must do manually if you haven't yet:

  1. Setup default url options for your specific environment. Here is an
     example of development environment:

       config.action_mailer.default_url_options = { :host => 'localhost:3000' }

     This is a required Rails configuration. In production it must be the
     actual host of your application

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root :to => "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

===============================================================================
Configuring: devise mailer
Configuring: devise authentication filter
rails g devise:users --orm active_record --admin-user --no-gems
         run  rails g devise:users --orm active_record --admin-user --no-gems from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
Configure Devise Users
rails g devise user
         run  rails g devise user from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
      invoke  active_record
      create    app/models/user.rb
      invoke    test_unit
      create      test/unit/user_test.rb
      create      test/fixtures/users.yml
      create    db/migrate/20101218104720_devise_create_users.rb
      insert    app/models/user.rb
       route  devise_for :users
create_admin_user
rails g devise admin
         run  rails g devise admin from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
      invoke  active_record
      create    app/models/admin.rb
      invoke    test_unit
      create      test/unit/admin_test.rb
      create      test/fixtures/admins.yml
      create    db/migrate/20101218104725_devise_create_admins.rb
      insert    app/models/admin.rb
       route  devise_for :admins
subclass: admin
superclass: User
rails g cancan:config --orm active_record --no-gems
         run  rails g cancan:config --orm active_record --no-gems from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
Insert cancan rescue statement into application controller
rails g roles:config --orm active_record --roles guest admin --strategy admin_flag
         run  rails g roles:config --orm active_record --roles guest admin --strategy admin_flag from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
     gemfile  roles_active_record
         run  bundle install from "."
Using rake (0.8.7) 
Using abstract (1.0.0) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.13) 
Using rack-test (0.5.6) 
Using tzinfo (0.3.23) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.12) 
Using actionmailer (3.0.3) 
Using arel (2.0.6) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using bcrypt-ruby (2.1.2) 
Using bundler (1.0.7) 
Using cancan (1.4.1) 
Using log4r (1.1.9) 
Using require_all (1.2.0) 
Using mocha (0.9.10) 
Using sugar-high (0.3.1) 
Using logging_assist (0.1.6) 
Using thor (0.14.6) 
Using railties (3.0.3) 
Using rails (3.0.3) 
Using migration_assist (0.1.7) 
Using rails3_assist (0.3.3) 
Using rspec-core (2.3.1) 
Using diff-lcs (1.1.2) 
Using rspec-expectations (2.3.0) 
Using rspec-mocks (2.3.0) 
Using rspec (2.3.0) 
Using rails3_artifactor (0.3.2) 
Using cancan-permits (0.3.6) 
Using code-spec (0.2.9) 
Using file-spec (0.1.4) 
Using rails-app-spec (0.3.2) 
Using test-unit (2.1.2) 
Using generator-spec (0.7.1) 
Using r3_plugin_toolbox (0.4.0) 
Using cancan-rest-links (0.2.0) 
Using warden (1.0.3) 
Using devise (1.1.5) 
Using devise-links (0.2.1) 
Using cream (0.8.1) 
Using meta_where (0.9.9.2) 
Using roles_generic (0.3.3) 
Using roles_active_record (0.3.4) 
Your bundle is complete! It was installed into /Users/kristianconsult/.rvm/gems/ruby-1.9.3-head
[Rails3::Assist::Logging]
rails g active_record:roles User --strategy admin_flag --roles guest admin --default-roles
         run  rails g active_record:roles User --strategy admin_flag --roles guest admin --default-roles from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
apply_role_strategy for : admin_flag in model User
      insert  app/models/user.rb
rails g permits:config --orm active_record --roles guest admin --no-gems
         run  rails g permits:config --orm active_record --roles guest admin --no-gems from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
[Rails3::Assist::Logging]
Configure Permits
rails g cancan:permits --roles ["guest", "admin"] --orm active_record
         run  rails g cancan:permits --roles ["guest", "admin"] --orm active_record from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
      create  app/permits/guest_permit.rb
      create  app/permits/admin_permit.rb
      create  app/permits/any_permit.rb
      create  app/permits/system_permit.rb
rails g cancan:licenses
         run  rails g cancan:licenses from "."
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/Users/kristianconsult/.rvm/gems/ruby-1.9.3-head/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
      create  app/licenses/user_admin_license.rb
      create  app/licenses/blogging_license.rb
</pre>

**Comment by bobics** [comment]
Thanks for the super quick fix.  When I try and update to cream 0.8.2, however, I get the error below from rubygems.  Looks like the latest rails3_artifactor is 0.3.1.

cream requires rails3_artifactor (>= 0.3.2, runtime).

**Comment by kristianmandrup** [comment]
Oh, sorry. I forgot to release the latest version of rails3_artifactor (0.3.2). It has now been released to rubygems, please try again ;)
Maybe just: $ bundle update rails3_artifactor

Good luck ;)

If you have more problems, you can go into "debugging" mode, by adding a :path option to any of the gems and then reference a local clone of the given repository of a gem, fx

gem 'cream', :path => '/my/path/to/gem'

Then any edit in the code is immediately reflected when you try to run it from the rails app.

**Comment by bobics** [comment]
Thanks for the tip!  I'll try checking out the issue myself (won't be able to take a look at it until tomorrow).  Looks like I'm still getting an error after updating (I omitted all the output except the exception this time):

```
     run  rails g permits:config --orm active_record --roles guest admin --no-gems from "."
```

/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:5: warning: already initialized constant INIT
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/extender/util.rb:6: warning: already initialized constant ACTIVE_MODULES
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/r3_plugin_toolbox-0.4.0/lib/r3_plugin_toolbox/macro.rb:15: warning: already initialized constant MACRO
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:184:in `escape': can't convert Symbol into String (TypeError)
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:184:in`file_names'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:184:in `map'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/sugar-high-0.3.1/lib/sugar-high/file.rb:184:in`file_names'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:18:in `role_strategies'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:22:in`has_strategy?'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:31:in `cardinality'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:30:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:30:in `cardinality'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/roles_generic-0.3.3/lib/roles_generic/strategy.rb:39:in`use_roles_strategy'
    from /Users/bobics/Development/testapps/cream_test/app/models/user.rb:1
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in`load_file'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:453:in`load_file'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:340:in `require_or_load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:491:in`load_missing_constant'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:183:in `const_missing'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:181:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:181:in `const_missing'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rspec-core-2.3.1/lib/rspec/core/backward_compatibility.rb:20:in`const_missing'
    from /Users/bobics/Development/testapps/cream_test/app/models/admin.rb:1
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:454:in`load_file'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:453:in`load_file'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:340:in `require_or_load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:491:in`load_missing_constant'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:183:in `const_missing'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:181:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:181:in `const_missing'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rspec-core-2.3.1/lib/rspec/core/backward_compatibility.rb:20:in`const_missing'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/inflector/methods.rb:113:in `constantize'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/inflector/methods.rb:112:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/inflector/methods.rb:112:in `constantize'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:528
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:538:in`call'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:538:in `default'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:538:in`[]'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:538:in `get'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise/mapping.rb:69:in`to'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise/rails/routes.rb:140:in `devise_for'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise/rails/routes.rb:136:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/devise-1.1.5/lib/devise/rails/routes.rb:136:in `devise_for'
    from /Users/bobics/Development/testapps/cream_test/config/routes.rb:2
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:233:in`instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:233:in `draw'
    from /Users/bobics/Development/testapps/cream_test/config/routes.rb:1
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in`load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:235:in `load'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:127:in`reload_routes!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:127:in `each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:127:in`reload_routes!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:120:in `routes_reloader'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/file_update_checker.rb:32:in`call'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/file_update_checker.rb:32:in `execute_if_updated'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application/finisher.rb:51
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application/finisher.rb:52:in`call'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application/finisher.rb:52
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `instance_exec'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`run'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:50:in `run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`each'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `run_initializers'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:134:in`initialize!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in `send'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:77:in`method_missing'
    from /Users/bobics/Development/testapps/cream_test/config/environment.rb:5
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/application.rb:103:in `require_environment!'
    from /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:16
    from script/rails:6:in`require'
    from script/rails:6

**Comment by kristianmandrup** [comment]
I think this is an issue with ruby 1.8.7. I have only tested cream with ruby 1.9 and above and I just have someone else reporting the same kind of problem with ruby 1.8.7.
Please try to upgrade to 1.9 and tell me if that works for you ;)

**Comment by kristianmandrup** [comment]
The other guy just upgraded to ruby 1.9.2 and cream then works. 
So this is a ruby 1.9.2 issue only.

**Comment by bobics** [comment]
Thanks for the update.  I actually tried debugging it a bit (got errors when only using Roles Generic and Roles Active Record gems) and after a while was thinking of trying upgrading to Ruby 1.9.2 but abandoned my efforts at that point.  Unfortunately atm I can't switch over to 1.9.2 (using REE 1.8.7), but I'll take a look at it soon after some due diligence with 1.9.2.

**Comment by kristianmandrup** [comment]
You can play with it using RVM. That way you can still keep your 1.8.7 REE system install and just play around with "virtual ruby" installations ;)

http://rvm.beginrescueend.com/
